### ISSUE TITLE
Inconsistent MD5 sum for sundials-3.1.0 for OS X

### ISSUE THREAD

**Issue by bjodah** [conda-forge/sundials-feedstock#22]
I get md5sum mismatch when trying to build a recipe using sundials-3.1.0:

https://travis-ci.org/bjodah/pycvodes/builds/407614803#L316
(from https://github.com/bjodah/pycvodes/pull/82)

To me it looks like there are 2 files corresponding to the same version and hash (!):
https://anaconda.org/conda-forge/sundials/files

Any clue how to get around this? (The files were uploaded at the same time as v3.1.1 was added, @jschueller  do you have any idea what might be the cause of this?)

**Comment by jschueller** [comment]
It seems there are several jobs run; one per python version although this recipe is a lib and not a Python module.

**Comment by jschueller** [comment]
It should be okay now, @bjodah

**Comment by bjodah** [comment]
Excellent, and big thanks for fixing this so quickly.
